/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiBoardRouteImport } from './routes/api/board'
import { Route as ApiBoardTeamSprintRouteImport } from './routes/api/board.$team.$sprint'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBoardRoute = ApiBoardRouteImport.update({
  id: '/api/board',
  path: '/api/board',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBoardTeamSprintRoute = ApiBoardTeamSprintRouteImport.update({
  id: '/$team/$sprint',
  path: '/$team/$sprint',
  getParentRoute: () => ApiBoardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/board': typeof ApiBoardRouteWithChildren
  '/api/board/$team/$sprint': typeof ApiBoardTeamSprintRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/board': typeof ApiBoardRouteWithChildren
  '/api/board/$team/$sprint': typeof ApiBoardTeamSprintRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/board': typeof ApiBoardRouteWithChildren
  '/api/board/$team/$sprint': typeof ApiBoardTeamSprintRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/board' | '/api/board/$team/$sprint'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/board' | '/api/board/$team/$sprint'
  id: '__root__' | '/' | '/api/board' | '/api/board/$team/$sprint'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiBoardRoute: typeof ApiBoardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/board': {
      id: '/api/board'
      path: '/api/board'
      fullPath: '/api/board'
      preLoaderRoute: typeof ApiBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/board/$team/$sprint': {
      id: '/api/board/$team/$sprint'
      path: '/$team/$sprint'
      fullPath: '/api/board/$team/$sprint'
      preLoaderRoute: typeof ApiBoardTeamSprintRouteImport
      parentRoute: typeof ApiBoardRoute
    }
  }
}

interface ApiBoardRouteChildren {
  ApiBoardTeamSprintRoute: typeof ApiBoardTeamSprintRoute
}

const ApiBoardRouteChildren: ApiBoardRouteChildren = {
  ApiBoardTeamSprintRoute: ApiBoardTeamSprintRoute,
}

const ApiBoardRouteWithChildren = ApiBoardRoute._addFileChildren(
  ApiBoardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiBoardRoute: ApiBoardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
